[[constraint]]
  branch = "master"
  name = "github.com/dghubble/go-twitter"

[[constraint]]
  name = "github.com/dghubble/oauth1"
  version = "0.5.0"

[[constraint]]
  name = "github.com/kubeless/kubeless"
  version = "1.0.1"
